# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 94a7b208fa30b046e860572029d73ca5cbdc14c459bb8b3a22ed366c472f0c5f6f6aeec283edbe51386f881460e9a16f3f64ba49a05f2c16d2b0307cc38908d5

test:
  secret_key_base: 688e55ddb07f351ad8f4b1bf1a7edbe826d32585ca2e0edc03f40ae3c3cc4e3299e58da1a326cd81154502aa70dcfb46ca5061f0ec3cf7053c07b6a28d5d962c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
